import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    main:{
        backgroundColor:'#2179b8',
        height:'100%',
        padding:15,
        alignContent:'center',
    },
    window_title:{
        marginBottom:20
    },
    window_title_text:{
        fontSize:48,
        color:'#fafafa',
        textAlign:'center',
        fontFamily:'Ubuntu-Light',
    },
    score_summary:{
        flexDirection:'row',
        paddingBottom:25,
        borderBottomColor:'#fafafa',
        borderBottomWidth:1
    },
    score_victories:{
        color:'#0fd945',
        fontSize:20,
        fontFamily:'Ubuntu-Light',
        flex:1,
        textAlign:'center',
        justifyContent:'center',
        borderRightColor:'#fafafa',
        borderRightWidth:1
    },
    score_defeats:{
        color:'#de1610',
        fontSize:20,
        flex:1,
        textAlign:'center',
        borderRightColor:'#fafafa',
        borderRightWidth:1,
        fontFamily:'Ubuntu-Light',
    },
    score_points:{
        color:'#d1c308',
        fontSize:20,
        flex:1,
        textAlign:'center',
        fontFamily:'Ubuntu-Light'
    },
    event_board:{
        width:"100%",
        marginTop:"10%"
    },
    event_card:{
        width:"100%",
        backgroundColor:"#2796e6",
        borderColor:'black',
        borderWidth:2,
        borderRadius:5,
        padding:10,
        flex:1, 
        flexDirection:'row',
        marginBottom:20
    },
    winning_team_picture:{
        alignContent:'flex-start',
        padding:10,
        width:64,
        height:64,
    },
    winning_team:{
        flex:0.25
    },
    event_result_text_victory:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#0fd945'
    },
    event_result_text_defeat:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#de1610'
    },
    event_scores:{
        flexDirection:'row',
        flex:0.5,
    },
    event_details:{
        flex:0.75,
        marginRight:20,
        flexDirection:'column'
    },
    event_points:{
        width:"100%"
    },
    event_score_text_terra:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#FF8C91'
    },
    event_score_text_ocean:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#47C4FF'
    },
    event_score_text_windy:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#82FF8A'
    },
    event_score_text_user:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#d1c308'
    },
    event_score_text_sep:{
        fontSize:24,
        fontFamily:'Ubuntu-Light',
        color:'#fafafa'
    },
    event_date_text:{
        fontSize:14,
        fontFamily:'Ubunutu-Light',
        color:'#fafafa'
    }
});