/**
 * This stylesheet has been obtained from Charles Hampton-Evans' [ID:1804656] CS310 Project, who is a member of the front-end team.
 */

import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    main:{
        flex: 1,
        backgroundColor: '#2179b8',
        alignItems:"center",
        alignContent:"center",
        width:"100%",
        height:"100%"
    },
    background:{
        backgroundColor: '#2179b8',
    },
    welcome_title:{
        alignItems:"center",
        backgroundColor:'#2179b8',
        top:"5%",
        paddingBottom:"2%",
        position:'relative'
    },
    title_text:{
        fontSize:36,
        color:"#fafafa",
        paddingBottom:"10%",
        textAlign:"justify",
        fontFamily:'Ubuntu-Light'
    },
    body_explanation:{
        alignContent:"center"
    },
    body_text:{
        fontSize:20,
        color:"#fafafa",
        paddingBottom:"5%",
        fontFamily:'Ubuntu-Light'
    },
    create_profile:{
        width:"85%"
    },
    form_inputs:{
        paddingTop:10,
        width:"100%",
        left:"5%"
    },
    form_input:{
        fontFamily:'Ubuntu-Light',
        borderColor:"#e8e1df",
        borderWidth:1,
        width:350,
        paddingBottom:10,
        color:"#fafafa",
        backgroundColor:"#2179b8"
    },
    form_input_title:{
        width:"100%",
        color:"#fafafa"
    },
    continue_button:{
        paddingTop:20,
        width:"90%",
    },
    character_counter:{//Kind of want this in the centre but fix later
        paddingTop:20
    },
    chartext:{
        color:"#fafafa"
    },
    avatar:{
        width:256,
        height:256,
    },
    welcome_text:{
        fontSize:24,
        color:'#fafafa'
    },
    welcome_view:{
        paddingTop:"30%",
        width:"90%",
        paddingBottom:"40%"
    },
    mascot_terra:{
        height:"100%",
        backgroundColor:"#edf5f3",
        borderWidth:1,
        borderColor:"grey",
        width:"100%",
        height:"100%"
    },
    mascot_ocean:{
        height:"100%",
        backgroundColor:"#edf5f3",
        borderWidth:1,
        borderColor:"grey",
        width:"100%",
        height:"100%"
    },
    mascot_windy:{
        height:"100%",
        backgroundColor:"#edf5f3",
        borderWidth:1,
        borderColor:"grey",
        width:"100%",
        height:"100%"
    },
    mascots:{
        width:"90%",
        paddingBottom:10,
        height:"15%",
    },
    mascot_information:{
        width:"66%",
        paddingLeft:10
    },
    mascot_image:{
        alignItems:'flex-end',
        paddingRight:10,
        bottom:15,
        flex:1,
        right:0,
        position:'absolute'
    },
    mascot_title_text:{
        fontSize:22,
        color:"#fafafa",
        fontFamily:'Ubuntu-Light'
    },
    mascot_info_text:{
        fontSize:14,
        color:"#fafafa",
        fontFamily:'Ubuntu-Light'
    },
    mascot_container:{
        flex:2
    }
});

export {styles};